### ISSUE TITLE
Tarball name

### ISSUE THREAD

**Issue by mcepl** [dephell/dephell_changelogs#3]
Are you certain that the name of the tarball should be ``v.0.0.1.tar.gz`` and not ``v0.0.1.tar.gz`` (notice the leading dot)?

**Comment by orsinium** [comment]
Are you about source code download link on Github? It is generated by Github itself from the tag name. The tag name is created by DepHell from the user-provided template (I used `--tag="v."`). There is no RFC, PEP, or any other standard about it AFAIK. So, no, I'm not certain about neither `v` nor `v.`.

**Comment by mcepl** [comment]
My suggestion was to use ``--tag="v"``, of course. ``v.0.0.1`` implies to me that the version number is ``.0.0.1`` (with leading dot), but I may be wrong.

**Comment by orsinium** [comment]
`v` is an abbreviation. Anyway, I've seen both approaches and no standard for it. That's an opinionated thing. DepHell itself can parse both forms, so no issues here.

Anyway, thank you for asking :)
